import clsx from "clsx";

const statusMap: Record<string, string> = {
  ACTIVE: "success",
  TRIAL: "info",
  EXPIRING: "warning",
  EXPIRED: "danger",
  ERROR: "danger",
  CRITICAL: "danger",
  WARNING: "warning",
  INFO: "info",
  DRAFT: "info",
  PAUSED: "warning",
  CANCELLED: "danger",
  SUSPENDED: "danger",
  LEAD: "info",
  ARCHIVED: "danger",
  NEW: "info",
  CONTACTED: "warning",
  IN_PROGRESS: "warning",
  CLOSED: "success",
  LOST: "danger",
  LOW: "info",
  NORMAL: "info",
  HIGH: "warning",
  URGENT: "danger",
  SENT: "warning",
  ACCEPTED: "success",
  REJECTED: "danger",
  PENDING: "warning",
  COMPLETED: "success",
  PENDING_PAYMENT: "warning",
  INVOICED: "info",
  PAID: "success",
};

const statusLabels: Record<string, string> = {
  ACTIVE: "Activa",
  TRIAL: "Trial",
  EXPIRING: "Pendiente renovacion",
  EXPIRED: "Expirada",
  ERROR: "Error",
  CRITICAL: "Critico",
  WARNING: "Aviso",
  INFO: "Info",
  DRAFT: "Borrador",
  PAUSED: "Pausada",
  CANCELLED: "Cancelada",
  SUSPENDED: "Suspendida",
  LEAD: "Potencial",
  ARCHIVED: "Archivado",
  NEW: "Nueva",
  CONTACTED: "Contactado",
  IN_PROGRESS: "En curso",
  CLOSED: "Cerrada",
  LOST: "Perdida",
  LOW: "Baja",
  NORMAL: "Normal",
  HIGH: "Alta",
  URGENT: "Urgente",
  SENT: "Enviado",
  ACCEPTED: "Aceptado",
  REJECTED: "Rechazado",
  PENDING: "Pendiente",
  COMPLETED: "Completado",
  PENDING_PAYMENT: "Pendiente de cobrar",
  INVOICED: "Facturado",
  PAID: "Cobrado",
};

export function StatusBadge({ value }: { value: string }) {
  return <span className={clsx("badge", statusMap[value] ?? "info")}>{statusLabels[value] ?? value}</span>;
}
